### ISSUE TITLE
FastText Error

### ISSUE THREAD

**Issue by j6mes** [UKPLab/fever-2018-team-athene#1]
Following the install instructions, I encounter the following error with FastText 

```
INFO:pipeline:=========================== Subtask 2. Sentence Retrieval ==========================================
[INFO] 2019-02-20 13:40:23,889 - pipeline - Starting data pre-processing...
INFO:pipeline:Starting data pre-processing...
/fever/test_data.p
./data/fasttext/fasttext.p
Model file cannot be opened for loading!
Traceback (most recent call last):
  File "src/scripts/athene/pipeline.py", line 153, in <module>
    sentence_retrieval_ensemble(logger)
  File "src/scripts/athene/pipeline.py", line 90, in sentence_retrieval_ensemble
    sentence_retrieval_ensemble_entrance(_args)
  File "/fever/src/athene/retrieval/sentences/ensemble.py", line 265, in entrance
    random_seed=args.random_seed, reserve_embed=args.reserve_embed)
  File "/fever/src/athene/retrieval/sentences/data_processing/data.py", line 33, in __init__
    self.data_pipeline()
  File "/fever/src/athene/retrieval/sentences/data_processing/data.py", line 71, in data_pipeline
    embed_dict = self.load_fasttext(self.iword_dict)
  File "/fever/src/athene/retrieval/sentences/data_processing/data.py", line 344, in load_fasttext
    model = FastText(self.fasttext_path)
  File "src/pyfasttext.pyx", line 196, in pyfasttext.FastText.__cinit__
  File "src/pyfasttext.pyx", line 666, in pyfasttext.FastText.load_model
RuntimeError: fastext tried to exit: 1
```

In the config file, I see the fasttext path is `"fasttext_path": "./data/fasttext/fasttext.p"`

But after following the setup instructions, I do not have that file:

```
ls -alh data/fasttext/
total 15G
drwxr-xr-x 1 root root 4.0K Feb 20 12:43 .
drwxr-xr-x 1 root root 4.0K Feb 20 13:07 ..
-rw-r--r-- 1 root root 8.0G Oct 19  2017 wiki.en.bin
-rw-rw-r-- 1 root root 6.2G Sep 19  2016 wiki.en.vec
```
How should that file be generated? Or should I just update the config file to use one of these?

**Comment by littsler** [comment]
It should be the wiki.en.bin file. Sorry for the mistake.

**Comment by j6mes** [comment]
Thanks. I can confirm that fixes it for me.
